### ISSUE TITLE
SubclassNotFound when using acts_as_singleton with ActiveRecord inheritance

### ISSUE THREAD

**Issue by kjvarga** [stephencelis/acts_as_singleton#1]
Hi,

I have the following setup:

```
class VirtualPlaylist < ActiveRecord::Base; acts_as_singleton; end
class MyFavorites < VirtualPlaylist; end
class RecentlyPlayedSongs < VirtualPlaylist; end
```

Accessing the singletons fails in this case with the following error:

```
musicsocial> VirtualPlaylist.instance
=> #<VirtualPlaylist name: nil, type: nil>
musicsocial> MyFavorites.instance
=> #<MyFavorites name: nil, type: "MyFavorites">
musicsocial> MyFavorites.instance
ActiveRecord::SubclassNotFound: The single-table inheritance mechanism failed to locate the subclass: 'MyFavorites'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite MyFavorites.inheritance_column to use another column for that information.
    from /Users/karl/projects/musicsocial/vendor/rails/activerecord/lib/active_record/base.rb:1637:in `instantiate_without_polymorphic_checks'
    from /Users/karl/projects/musicsocial/vendor/plugins/has_many_polymorphs/lib/has_many_polymorphs/base.rb:52:in `instantiate'
    from /Users/karl/projects/musicsocial/vendor/rails/activerecord/lib/active_record/base.rb:661:in `find_by_sql'
    from /Users/karl/projects/musicsocial/vendor/rails/activerecord/lib/active_record/base.rb:661:in `collect!'
    from /Users/karl/projects/musicsocial/vendor/rails/activerecord/lib/active_record/base.rb:661:in `find_by_sql'
    from /Users/karl/projects/musicsocial/vendor/rails/activerecord/lib/active_record/base.rb:1548:in `find_every'
    from /Users/karl/projects/musicsocial/vendor/rails/activerecord/lib/active_record/base.rb:1505:in `find_initial'
    from /Users/karl/projects/musicsocial/vendor/rails/activerecord/lib/active_record/base.rb:613:in `find'
    from /Users/karl/projects/musicsocial/vendor/rails/activerecord/lib/active_record/base.rb:623:in `first'
    from /Users/karl/projects/musicsocial/vendor/plugins/acts_as_singleton/lib/acts_as_singleton.rb:42:in `instance'
    from (irb):4
```

However if I comment out the line in acts_as_singleton.rb which privatizes a bunch of the instance methods, it works.

```
#private_class_method *methods.grep(PRIVATE) # Deny existent others.

musicsocial> VirtualPlaylist.instance
=> #<VirtualPlaylist name: nil, type: nil>
musicsocial> MyFavorites.instance
=> #<MyFavorites name: nil, type: "MyFavorites">
musicsocial> RecentlyPlayedSongs.instance
=> #<RecentlyPlayedSongs name: nil, type: "RecentlyPlayedSongs">
```

I'm not sure which method it is that is causing the problem.

Regards,
Karl

**Comment by stephencelis** [comment]
Don't make ActiveRecord::Base.allocate private [closed by 72280ff13b96ef51055d88111a7c34dd0e8d8452].
