### ISSUE TITLE
rails 3 compatibility issues with find_by_sql again

### ISSUE THREAD

**Issue by troessner** [stephencelis/acts_as_singleton#5]
Given this simple model

```
class Platform < ActiveRecord::Base
  acts_as_singleton
end
```

and using 3.1.0.rc4 I get the following error when doing a

```
 Platform.instance
```

in the rails console:

```
>> Platform.instance
ArgumentError: wrong number of arguments (2 for 1)
from /home/wtf/.rvm/gems/ruby-1.9.2-p180@satellite/bundler/gems/acts_as_singleton-4229bec5929a/lib/acts_as_singleton.rb:58:in `find_by_sql'
from /home/wtf/.rvm/gems/ruby-1.9.2-p180@satellite/gems/activerecord-3.1.0.rc4/lib/active_record/relation.rb:109:in `to_a'
from /home/wtf/.rvm/gems/ruby-1.9.2-p180@satellite/gems/activerecord-3.1.0.rc4/lib/active_record/relation/finder_methods.rb:370:in `find_first'
from /home/wtf/.rvm/gems/ruby-1.9.2-p180@satellite/gems/activerecord-3.1.0.rc4/lib/active_record/relation/finder_methods.rb:122:in `first'
from /home/wtf/.rvm/gems/ruby-1.9.2-p180@satellite/gems/activerecord-3.1.0.rc4/lib/active_record/base.rb:444:in `first'
from /home/wtf/.rvm/gems/ruby-1.9.2-p180@satellite/bundler/gems/acts_as_singleton-4229bec5929a/lib/acts_as_singleton.rb:43:in `instance'
from (irb):1
from /home/wtf/.rvm/gems/ruby-1.9.2-p180@satellite/gems/railties-3.1.0.rc4/lib/rails/commands/console.rb:45:in `start'
from /home/wtf/.rvm/gems/ruby-1.9.2-p180@satellite/gems/railties-3.1.0.rc4/lib/rails/commands/console.rb:8:in `start'
from /home/wtf/.rvm/gems/ruby-1.9.2-p180@satellite/gems/railties-3.1.0.rc4/lib/rails/commands.rb:40:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>
```

Even when using the most recent version via adding this line

```
gem 'acts_as_singleton',  :git => 'https://github.com/stephencelis/acts_as_singleton.git'
```

to my Gemfile.

It seems to be the same issue as here: https://github.com/stephencelis/acts_as_singleton/issues/3

Any ideas?

**Comment by stephencelis** [comment]
It looks like Rails 3.1 has changed things a bit. I can take a quick look this evening, but feel free to submit a patch in the meantime if you dug into it at all.

**Comment by stephencelis** [comment]
Changing `find_by_sql(sql)` to `find_by_sql(*)` should fix things. I'll try to get a patch out tonight if you don't tackle it.

**Comment by troessner** [comment]
Great, thanks!

**Comment by stephencelis** [comment]
Pushed.

``` ruby
gem 'acts_as_singleton', '~> 0.0.6.beta'
```

**Comment by troessner** [comment]
Works like a charm!
Thanks a lot for the quick response.
