### ISSUE TITLE
rails 3.1 is out

### ISSUE THREAD

**Issue by troessner** [stephencelis/acts_as_singleton#6]
...and bundle update rails fails with:

```
bundle update rails
Fetching source index for http://rubygems.org/
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    railties (~> 3.1.0.rc1) depends on
      activesupport (= 3.1.0.rc1)

    acts_as_singleton (= 0.0.6.beta) depends on
      activesupport (3.1.0.rc4)
```

**Comment by troessner** [comment]
Seems to be a non trivial issue: Upgrading to rails 3.1 breaks the tests:

```
  7) Error:
test_should_honor_polymorphism(ActsAsSingletonTest):
NoMethodError: private method `finder_needs_type_condition?' called for #<Class:0x9df0d8c>
    /home/troessner/.rvm/gems/ruby-1.9.2-p290@acts_as_singleton/gems/activerecord-3.1.0/lib/active_record/base.rb:1082:in `method_missing'
    /home/troessner/.rvm/gems/ruby-1.9.2-p290@acts_as_singleton/gems/activerecord-3.1.0/lib/active_record/base.rb:1949:in `ensure_proper_type'
    /home/troessner/.rvm/gems/ruby-1.9.2-p290@acts_as_singleton/gems/activerecord-3.1.0/lib/active_record/base.rb:1556:in `initialize'
    /home/troessner/.rvm/gems/ruby-1.9.2-p290@acts_as_singleton/gems/activerecord-3.1.0/lib/active_record/base.rb:508:in `new'
    /home/troessner/.rvm/gems/ruby-1.9.2-p290@acts_as_singleton/gems/activerecord-3.1.0/lib/active_record/base.rb:508:in `create'
    /home/troessner/dev/acts_as_singleton/lib/acts_as_singleton.rb:43:in `instance'
    /home/troessner/dev/acts_as_singleton/test/acts_as_singleton_test.rb:104:in `block in <class:ActsAsSingletonTest>'
```

**Comment by stephencelis** [comment]
Fixed, thanks!

```
Pushing gem to https://rubygems.org...
Successfully registered gem: acts_as_singleton (0.0.7)
```
